package types

const (
	SPICE_CHANNEL_MAIN      uint8 = 1
	SPICE_CHANNEL_DISPLAY   uint8 = 2
	SPICE_CHANNEL_INPUTS    uint8 = 3
	SPICE_CHANNEL_CURSOR    uint8 = 4
	SPICE_CHANNEL_PLAYBACK  uint8 = 5
	SPICE_CHANNEL_RECORD    uint8 = 6
	SPICE_CHANNEL_TUNNEL    uint8 = 7 // obsolete
	SPICE_CHANNEL_SMARTCARD uint8 = 8
	SPICE_CHANNEL_USBREDIR  uint8 = 9
	SPICE_CHANNEL_PORT      uint8 = 10
	SPICE_CHANNEL_WEBDAV    uint8 = 11
)
